---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: check formatting
    image: gradle:jdk17-alpine
    commands:
      - ./gradlew lintKotlin

  - name: build the project
    user: root
    # image: cimg/android:2022.12
    image: gradle:jdk17-alpine
    commands: 
      - ./gradlew assembleDebug
